version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
  kafka:
    image: wurstmeister/kafka:2.12-2.5.0
    links:
     - zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "writer"
  apache:
    build: apache
    links:
     - location
     - book
     - consumer
    ports:
     - "8080:80"
  #postgres:
  #  build: postgres
  #  environment:
  #    POSTGRES_PASSWORD: dbpass
  #    POSTGRES_USER: dbuser
  location:
    build: ../location
    links:
     - kafka
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
  book:
    build: ../book
    links:
     - kafka
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
  consumer:
    build: ../consumer
    links:
     - kafka
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092

